# Generated by Django 5.0.6 on 2026-06-28 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketOdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_no', models.PositiveSmallIntegerField(unique=True)),
                ('a', models.FloatField()),
                ('d', models.FloatField()),
                ('b', models.FloatField()),
                ('a_adv', models.FloatField()),
                ('b_adv', models.FloatField()),
            ],
            options={
                'ordering': ['match_no'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('code', models.CharField(help_text="ISO flag code, ej. 'ar', 'gb-eng'", max_length=8)),
                ('elo', models.IntegerField(default=1700)),
                ('host', models.BooleanField(default=False)),
                ('stats', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-elo'],
            },
        ),
        migrations.CreateModel(
            name='TournamentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_open', models.PositiveSmallIntegerField(default=0)),
                ('rounds_enabled', models.JSONField(default=dict)),
                ('total_players', models.PositiveIntegerField(default=2480)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveSmallIntegerField()),
                ('index', models.PositiveSmallIntegerField()),
                ('winner', models.CharField(max_length=60)),
                ('score', models.CharField(blank=True, max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['round', 'index'],
                'unique_together': {('round', 'index')},
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_no', models.PositiveSmallIntegerField(unique=True)),
                ('date_label', models.CharField(blank=True, max_length=60)),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures_a', to='tournament.team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures_b', to='tournament.team')),
            ],
            options={
                'ordering': ['match_no'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveSmallIntegerField()),
                ('index', models.PositiveSmallIntegerField()),
                ('pick', models.CharField(blank=True, max_length=60)),
                ('goal_a', models.IntegerField(blank=True, null=True)),
                ('goal_b', models.IntegerField(blank=True, null=True)),
                ('pen', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['round', 'index'],
                'unique_together': {('user', 'round', 'index')},
            },
        ),
    ]
