# Generated by Django 5.0.6 on 2026-06-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BracketFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveSmallIntegerField()),
                ('index', models.PositiveSmallIntegerField()),
                ('team_a', models.CharField(blank=True, max_length=60)),
                ('team_b', models.CharField(blank=True, max_length=60)),
                ('date_label', models.CharField(blank=True, max_length=60)),
                ('confirmed', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['round', 'index'],
                'unique_together': {('round', 'index')},
            },
        ),
    ]
