# Generated by Django 5.0.6 on 2026-06-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_result_minute_result_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveSmallIntegerField()),
                ('index', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['round', 'index'],
                'unique_together': {('round', 'index')},
            },
        ),
    ]
